# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest


    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:    
      # Caching dependencies to speed up workflows. (GitHub will remove any cache entries that have not been accessed in over 7 days.)
      - name: Cache node modules
        uses: actions/cache@v2
        id: cache
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Hexo Action
      # You may pin to the exact commit or the version.
      # uses: sma11black/hexo-action@08f5143fa402cdaccf9fc016d6bc91329f082eb0
        uses: sma11black/hexo-action@v1.0.4
        with:
          # Github user name
          user_name: prettywinter # default is github-actions[bot]
          # Github email
          user_email: jhlzlove@163.com # default is 41898282+github-actions[bot]@users.noreply.github.com
          # The deploy key for Github Pages repo
          deploy_key: ${{ secrets.DEPLOY_SECRET}} # default is 
          # Git commit messages to your GitHub Pages repository.
          commit_msg: Automatic deploy by Github Action # optional, default is 