name: Hexo Deploy GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Build and Deploy
      uses: theme-keep/hexo-deploy-github-pages-action@master
      env:
        PERSONAL_TOKEN: ${{ secrets.DEPLOY_SECRET }}

        # The repository the action should deploy to.
        PUBLISH_REPOSITORY: git@github.com:prettywinter/prettywinter.github.io.git

        # The branch the action should deploy to.
        BRANCH: pages