name: Deploy

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{runner.OS}}-${{hashFiles('**/package-lock.json')}}
      - uses: yrpang/github-actions-hexo@v1.3
        with:
          deploykey: ${{secrets.DEPLOY_SECRET}}
          username: prettywinter
          email: jhlzlove@163.com
          if_keep_commit_history: true